# Generated by Django 4.0.1 on 2022-01-23 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.CharField(db_index=True, max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=7)),
                ('years_old', models.IntegerField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('moves', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.moves')),
            ],
        ),
    ]
