# Generated by Django 4.0.1 on 2022-01-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ('moves', 'time_create'), 'verbose_name': 'Наши спонсоры', 'verbose_name_plural': 'Наши спонсоры'},
        ),
        migrations.AlterField(
            model_name='players',
            name='moves',
            field=models.CharField(db_index=True, max_length=1023, verbose_name='Отчёт'),
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Вертухай'),
        ),
        migrations.AlterField(
            model_name='players',
            name='sex',
            field=models.CharField(max_length=7, verbose_name='Кто по жизни'),
        ),
        migrations.AlterField(
            model_name='players',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата смены'),
        ),
        migrations.AlterField(
            model_name='players',
            name='years_old',
            field=models.IntegerField(verbose_name='На сколько преисполнен'),
        ),
        migrations.DeleteModel(
            name='Moves',
        ),
    ]
