# Generated by Django 4.0.1 on 2022-01-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_players_options_alter_players_moves_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ('time_create',), 'verbose_name': 'Наши спонсоры', 'verbose_name_plural': 'Наши спонсоры'},
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Вертухай'),
        ),
        migrations.AlterField(
            model_name='players',
            name='sex',
            field=models.CharField(max_length=255, verbose_name='Кто по жизни'),
        ),
    ]
